CREATE DATABASE IF NOT EXISTS todolist;
USE todolist;
CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    done TINYINT DEFAULT 0
);
